# Generated by Django 2.1.4 on 2018-12-31 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
