# Generated by Django 2.1.4 on 2018-12-31 09:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_book_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issued_by',
            field=models.ManyToManyField(to='blogapp.Student'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=4, default=400.3, max_digits=19),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 9, 17, 7, 20905, tzinfo=utc)),
        ),
    ]
