# Generated by Django 2.1.4 on 2018-12-31 09:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_auto_20181231_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 9, 37, 32, 342849, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
