# Generated by Django 2.1.4 on 2018-12-31 09:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_auto_20181231_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ImageField',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='book',
            name='issued_by',
        ),
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 9, 43, 18, 844040, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
