# Generated by Django 2.1.4 on 2018-12-31 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0014_auto_20181231_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 12, 31, 10, 19, 20, 253748, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='book',
            name='issued_by',
        ),
        migrations.AddField(
            model_name='book',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blogapp.Student'),
        ),
    ]
